name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            ${{ secrets.DOCKER_USERNAME }}/api-pufa-computing:latest
            ${{ secrets.DOCKER_USERNAME }}/api-pufa-computing:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/api-pufa-computing:${{ github.ref }}

  deployments:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER }}
            username: ${{ secrets.SERVER_PASSWORD }}
            key: ${{ secrets.PROD_KEY }}
            script: |
              whoami
              docker stop api-pufa-computing || true && docker rm api-pufa-computing || true
              docker pull ${{ vars.IMAGE_NAME}}
              docker run -d -p 8080:5000 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME}}