name: CI PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          if [ ! -f .env ]; then
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
            echo "REDIS_PASS=${{ secrets.REDIS_PASS }}" >> .env
            echo "API_PORT=${{ secrets.API_PORT }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          fi

      - name: Ensure .env file exists
        run: touch .env

      - name: Connect to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            ${{ secrets.DOCKER_USERNAME }}/api-pufa-computing:latest

  deployments:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
              whoami
              docker stop api-pufa-computing || true && docker rm api-pufa-computing || true
              docker pull ${{ vars.IMAGE_NAME}}
              docker run -d -p ${{ secrets.API_PORT }}:${{ secrets.API_PORT }} --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME}}
